### ISSUE TITLE
npx gulp watch results in error

### ISSUE THREAD

**Issue by ccrutchf** [UCSD-E4E/website2.0#204]
```
[10:39:46] Error: ENOENT: no such file or directory, mkdir './cache/resize'
    at Object.mkdirSync (node:fs:1371:26)
    at handle_cache_updates (/home/chris/Repos/school/e4e/website2.0/gulpfile.js:101:12)
    at bound (node:domain:432:15)
    at runBound (node:domain:443:12)
    at asyncRunner (/home/chris/Repos/school/e4e/website2.0/node_modules/async-done/index.js:52:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
```

**Comment by ccrutchf** [comment]
`mkdir -p ./cache/resize` is a workaround here.
